version: 2
updates:
- package-ecosystem: gradle
  directory: "/garsson-api"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: org.flywaydb:flyway-core
    versions:
    - 7.5.2
    - 7.5.3
    - 7.5.4
    - 7.6.0
    - 7.7.0
    - 7.7.1
    - 7.7.2
    - 7.7.3
    - 7.8.0
    - 7.8.1
  - dependency-name: org.jetbrains.exposed:exposed
    versions:
    - 0.17.12
    - 0.17.8
    - 0.17.9
  - dependency-name: org.jetbrains.kotlin.jvm
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: io.undertow:undertow-core
    versions:
    - 2.2.3.Final
    - 2.2.4.Final
    - 2.2.5.Final
  - dependency-name: io.undertow:undertow-websockets-jsr
    versions:
    - 2.2.3.Final
    - 2.2.4.Final
    - 2.2.5.Final
  - dependency-name: com.fasterxml.jackson.datatype:jackson-datatype-jdk8
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.datatype:jackson-datatype-jsr310
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson:jackson-bom
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.module:jackson-module-parameter-names
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: org.postgresql:postgresql
    versions:
    - 42.2.18
    - 42.2.19
  - dependency-name: com.zaxxer:HikariCP
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: org.testcontainers:testcontainers
    versions:
    - 1.15.1
    - 1.15.2
